Models/Product.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public enum ProductType
    {
        Mouse,
        Headset,
        Keyboard,
        CPU,
        GPU,
        RAM,
        Display,
        PowerSupply
    }

    public class Product
    {
        public int Id { get; set; }
        [BindProperty]
        public ProductType ProductType { get; set; }
        [MaxLength(100)]
        public string Name { get; set; } = "";
        [MaxLength(100)]
        public string Brand { get; set; } = "";
        [Precision(16, 2)]
        public virtual decimal Price { get; set; }
        public string Description { get; set; } = "";
        [MaxLength(100)]
        public string ImageFileName { get; set; } = "";
        public DateTime CreatedAt { get; set; }
        public int StockCount {  get; set; }

    }
}

Pages/Admin/Orders/Create.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Store.Models;
using Store.Pages.Admin.Orders.Facade;
using static Store.Pages.Admin.Orders.Facade.OrderFacade;

namespace Store.Pages.Admin.Orders
{
    public class CreateModel : PageModel
    {
        private readonly OrderFacade _orderFacade;
        private readonly UserManager<User> _userManager;
        public List<Product> Products { get; set; }

        public CreateModel(OrderFacade orderFacade, UserManager<User> userManager)
        {
            _orderFacade = orderFacade;
            _userManager = userManager;
            Products = new List<Product>();
        }

        [BindProperty]
        public int ProductId { get; set; }

        [BindProperty]
        public int Quantity { get; set; }

        public async Task OnGetAsync()
        {
            if (Products == null)
            {
                Products = new List<Product>();
            }
            Products = await _orderFacade.GetAllProductsAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            try
            {
                var order = await _orderFacade.PlaceOrder(user.UserName, ProductId, Quantity);
                return RedirectToPage("./Index");
            }
            catch (NotEnoughInStockException ex)
            {
                TempData["Message"] = ex.Message;
                return Page();
            }
        }
    }
}

Pages/Admin/Orders/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Store.Models;
using Store.Services;

namespace Store.Pages.Admin.Orders
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Order Order { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Order = await _context.Orders.FirstOrDefaultAsync(m => m.Id == id);

            if (Order == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Order = await _context.Orders.FindAsync(id);

            if (Order != null)
            {
                _context.Orders.Remove(Order);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Store.Services;
using Store.Models;
using Store.Pages.Admin.Products.Builder;

namespace Store.Pages.Admin.Products
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly IProductBuilder _productBuilder;

        [BindProperty]
        public ProductType ProductType { get; set; }
        [BindProperty]
        public IFormFile ImageFile { get; set; }

        public CreateModel(ApplicationDbContext context, IProductBuilder productBuilder)
        {
            _context = context;
            _productBuilder = productBuilder;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                Product newProduct;

                var fileName = ProcessUploadedFile();

                if (fileName != null)
                {
                    newProduct = _productBuilder
                        .SetProductType(ProductType)
                        .SetName(Request.Form["Name"])
                        .SetBrand(Request.Form["Brand"])
                        .SetPrice(decimal.Parse(Request.Form["Price"]))
                        .SetStockCount(int.Parse(Request.Form["StockCount"]))
                        .SetDescription(Request.Form["Description"])
                        .SetImageFileName(fileName)
                        .SetProductDateTime(DateTime.Now)
                        .Build();
                }
                else
                {
                    throw new Exception("Image file is required.");
                }

                _context.Products.Add(newProduct);
                _context.SaveChanges();

                return RedirectToPage("/Admin/Products/Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"An error occurred: {ex.Message}");
                return Page();
            }
        }
        private string ProcessUploadedFile()
        {
            if (ImageFile == null)
            {
                return null;
            }

            var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/products", uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                ImageFile.CopyTo(fileStream);
            }

            return uniqueFileName;
        }

    }
}

Pages/Admin/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Store.Services;
using Store.Models;

namespace Store.Pages.Admin.Products
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        [BindProperty]
        public Product Product { get; set; }

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Products.FindAsync(id);

            if (Product != null)
            {

                _context.Products.Remove(Product);
                await _context.SaveChangesAsync();

                if (Product.ImageFileName != "DigitalClock.jpg" && Product.ImageFileName != "PocketCalculator.jpg" && Product.ImageFileName != "PortableRadio.jpg")
                {
                    var oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/products", Product.ImageFileName);
                    try
                    {
                        System.IO.File.Delete(oldFilePath);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Failed to delete file: {ex.Message}");
                    }
                }
            }

            return RedirectToPage("./Index");
        }
    }

}

Pages/Admin/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Store.Services;
using Store.Models;

namespace Store.Pages.Admin.Products
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        [BindProperty]
        public Product Product { get; set; }
        [BindProperty]
        public IFormFile ImageFile { get; set; }

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (ImageFile != null)
            {
                var fileName = ProcessUploadedFile();

                var old = Product.ImageFileName;

                Product.ImageFileName = fileName;

                var oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/products", old);
                if (System.IO.File.Exists(oldFilePath))
                {
                    try
                    {
                        System.IO.File.Delete(oldFilePath);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Failed to delete file: {ex.Message}");
                    }
                }
            }

            _context.Attach(Product).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();

            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(Product.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private string ProcessUploadedFile()
        {
            var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/products", uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                ImageFile.CopyTo(fileStream);
            }

            return uniqueFileName;
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }

}

Pages/Admin/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Store.Models;
using Store.Services;
using Store.Pages.Admin.Products;
using Store.Pages.Admin.Products.Prototype;
using Microsoft.AspNetCore.Identity;
using Store.Pages.Admin.Products.Strategy;
using Microsoft.EntityFrameworkCore;

namespace Store.Pages.Admin.Products
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext context;
        private readonly IProductFactory productFactory;
        private readonly ProductPrototype productPrototype;
        private readonly UserManager<User> _userManager;
        public List<Product> Products { get; set; } = new List<Product>();
        [BindProperty]
        public ProductType ProductType { get; set; }

        public IndexModel(ApplicationDbContext context, IProductFactory productFactory, ProductPrototype productPrototype, UserManager<User> userManager)
        {
            this.context = context;
            this.productFactory = productFactory;
            this.productPrototype = productPrototype;
            this._userManager = userManager;
        }

        public ISortStrategy SortStrategy { get; set; }
        public void SetSortStrategy(ISortStrategy sortStrategy)
        {
            SortStrategy = sortStrategy;
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                Product newProduct;
                if (ProductType == ProductType.Mouse || ProductType == ProductType.Headset || ProductType == ProductType.Keyboard)
                {
                    newProduct = productFactory.CreateProduct(ProductType);
                }
                else
                {
                    return RedirectToPage("/Admin/Products/Create");
                }

                context.Products.Add(newProduct);
                context.SaveChanges();
                return RedirectToPage("/Admin/Products/Index");
            }

            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"An error occurred: {ex.Message}");
                return Page();
            }
        }

        public IActionResult OnPostClone(int id)
        {
            var originalProduct = context.Products.Find(id);
            if (originalProduct == null)
            {
                return NotFound();
            }

            var clonedProduct = productPrototype.CloneProduct(originalProduct);
            context.Products.Add(clonedProduct);
            context.SaveChanges();

            return RedirectToPage("/Admin/Products/Index");
        }

        public async Task OnGetAsync(int? Id, string sortStrategy)
        {
            switch (sortStrategy)
            {
                case "stockcountAscending":
                    SetSortStrategy(new SortByStockCountAscending());
                    break;
                case "stockcountDescending":
                    SetSortStrategy(new SortByStockCountDescending());
                    break;
                case "priceAscending":
                    SetSortStrategy(new SortByPriceAscending());
                    break;
                case "priceDescending":
                    SetSortStrategy(new SortByPriceDescending());
                    break;
            }

            if (Id.HasValue)
            {
                Products = await context.Products
                    .Where(r => r.Id == Id.Value)
                    .ToListAsync();
            }
            else
            {
                Products = await context.Products
                    .ToListAsync();
            }

            if (SortStrategy != null)
            {
                Products = context.Products.OrderByDescending(p => p.Id).ToList();
            }
        }
    }
}

Pages/Admin/Products/Create.cshtml
@page
@model Store.Pages.Admin.Products.CreateModel

<h2 class="text-center mb-5">Create New Product</h2>

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="ProductType">Product Type:</label>
        <select class="form-control custom-select" id="ProductType" asp-for="ProductType">
            <option class="btn btn-outline-primary flex-shrink-0" value="CPU">CPU</option>
            <option class="btn btn-outline-primary flex-shrink-0" value="GPU">GPU</option>
            <option class="btn btn-outline-primary flex-shrink-0" value="Ram">Ram</option>
            <option class="btn btn-outline-primary flex-shrink-0" value="Display">Display</option>
            <option class="btn btn-outline-primary flex-shrink-0" value="PowerSupply">PowerSupply</option>
        </select>
    </div>
    <div class="form-group">
        <label for="Name">Product Name:</label>
        <input type="text" class="form-control" id="Name" name="Name" id="nameInput">
    </div>

    <div class="form-group">
        <label for="Brand">Product Brand:</label>
        <input type="text" class="form-control" id="Brand" name="Brand" id="brandInput">
    </div>

    <div class="form-group">
        <label for="Price">Product Price:</label>
        <input type="number" class="form-control" id="Price" name="Price" id="priceInput">
    </div>

    <div class="form-group">
        <label for="StockCount">Product Stock:</label>
        <input type="number" class="form-control" id="StockCount" name="StockCount" id="stockCountInput">
    </div>

    <div class="form-group">
        <label for="Description">Product Description:</label>
        <textarea class="form-control" id="Description" name="Description" id="descriptionInput"></textarea>
    </div>

    <div class="form-group" id="imageUpload">
        <label>Upload Image</label>
        <input type="file" asp-for="ImageFile" required>
    </div>

    <button type="submit" class="btn btn-outline-primary flex-shrink-0">Create</button>
</form>

Pages/Admin/Products/Delete.cshtml
@page
@model Store.Pages.Admin.Products.DeleteModel

<h2 class="text-center mb-5">Delete Product</h2>

<h3>Are you sure you want to delete this product?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Brand)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ImageFileName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ImageFileName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.CreatedAt)
        </dd>
    </dl>

    <form method="post">
        <input type="submit" value="Delete" class="btn btn-outline-danger flex-shrink-0" /> |
        <a href="./Index">Back to List</a>
    </form>
</div>

Pages/Admin/Products/Edit.cshtml
@page
@model Store.Pages.Admin.Products.EditModel

<h2 class="text-center mb-5">Edit Product</h2>

<form method="post" enctype="multipart/form-data">
    <input type="hidden" asp-for="Product.Id" />
    <div class="form-group">
        <label asp-for="Product.ProductType"></label>
        <select class="form-control" asp-for="Product.ProductType">
            <option value="Mouse">Mouse</option>
            <option value="Headset">Headset</option>
            <option value="Keyboard">Keyboard</option>
            <option value="CPU">CPU</option>
            <option value="GPU">GPU</option>
            <option value="RAM">RAM</option>
            <option value="Display">Display</option>
            <option value="PowerSupply">PowerSupply</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Product.Name"></label>
        <input class="form-control" asp-for="Product.Name" />
    </div>
    <div class="form-group">
        <label asp-for="Product.Brand"></label>
        <input class="form-control" asp-for="Product.Brand" />
    </div>
    <div class="form-group">
        <label asp-for="Product.Price"></label>
        <input class="form-control" asp-for="Product.Price" />
    </div>
    <div class="form-group">
        <label asp-for="Product.StockCount"></label>
        <input class="form-control" asp-for="Product.StockCount" />
    </div>
    <div class="form-group">
        <label asp-for="Product.Description"></label>
        <textarea class="form-control" asp-for="Product.Description"></textarea>
    </div>
    <div class="form-group">
        <label>Current Image</label>
        <img src="~/products/@Model.Product.ImageFileName" alt="Product Image" style="width: 100px; height: auto;" />
    </div>
    <div class="form-group">
        <label>Upload New Image</label>
        <input type="file" asp-for="ImageFile" />
    </div>
    <div class="form-group">
        <label asp-for="Product.CreatedAt"></label>
        <input class="form-control" asp-for="Product.CreatedAt" readonly />
    </div>
    <button type="submit" class="btn btn-outline-primary flex-shrink-0">Save</button>
    <a href="./Index">Back to List</a>
</form>

Pages/Admin/Products/Index.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using Store.Models
@model Store.Pages.Admin.Products.IndexModel
@{
}

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<h2 class="text-center mb-5">List of Products</h2>

<div class="d-flex justify-content-start align-items-center">
    <label for="sortStrategy" class="mr-2">Sort by:</label>
    <select id="sortStrategy" onchange="location = this.value;" class="form-control">
        <option value="">Select...</option>
        <option value="?sortStrategy=stockcountAscending">Stock Count (Ascending)</option>
        <option value="?sortStrategy=stockcountDescending">Stock Count (Descending)</option>
        <option value="?sortStrategy=priceAscending">Price (Ascending)</option>
        <option value="?sortStrategy=priceDescending">Price (Descending)</option>
    </select>
</div>

@{
    var message = TempData["Message"] as string;
    if (!string.IsNullOrEmpty(message))
    {
        <div class="alert alert-warning">
            @message
        </div>
    }
}

@if (SignInManager.IsSignedIn(User))
{
    if (User.IsInRole("admin"))
    {
        <div class="row mb-5">

            <form method="post" enctype="multipart/form-data">
                <div class="form-group text-center">
                    <select class="form-control custom-select" id="ProductType" asp-for="ProductType">
                        <option class="btn btn-outline-primary flex-shrink-0" value="Mouse">Mouse</option>
                        <option class="btn btn-outline-primary flex-shrink-0" value="Headset">Headset</option>
                        <option class="btn btn-outline-primary flex-shrink-0" value="Keyboard">Keyboard</option>
                        <option class="btn btn-outline-primary flex-shrink-0" value="CPU">CPU</option>
                        <option class="btn btn-outline-primary flex-shrink-0" value="GPU">GPU</option>
                        <option class="btn btn-outline-primary flex-shrink-0" value="RAM">RAM</option>
                        <option class="btn btn-outline-primary flex-shrink-0" value="Display">Display</option>
                        <option class="btn btn-outline-primary flex-shrink-0" value="PowerSupply">PowerSupply</option>
                    </select>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary flex-shrink-0 align-self-center">Create</button>
                </div>
            </form>

            <div class="col">
            </div>
        </div>

        @foreach (var product in Model.Products)
        {
            <section class="py-5">
                <div class="container px-4 px-lg-5 my-5">
                    <div class="row gx-4 gx-lg-5 align-items-center">
                        <div class="col-md-6">
                            <img class="card-img-top mb-5 mb-md-0" src="/products/@product.ImageFileName" alt="@product.Name" />
                        </div>
                        <div class="col-md-6">
                            <div class="small mb-1">ID: @product.Id</div>
                            <h1 class="display-5 fw-bolder">@product.Name</h1>
                            <div class="fs-5 mb-5">
                                <span>@(product.Price)$</span>
                            </div>
                            <p class="lead">@product.Description</p>
                            <p><strong>Brand:</strong> @product.Brand</p>
                            <p><strong>Stock:</strong> @product.StockCount</p>
                            <p><strong>Created At:</strong> @product.CreatedAt.ToString("MM/dd/yyyy")</p>

                            <a class="btn btn-outline-dark flex-shrink-0" href="/Admin/Products/Edit?id=@product.Id">Edit</a>
                            <a class="btn btn-outline-danger flex-shrink-0" href="/Admin/Products/Delete?id=@product.Id">Delete</a>
                            <form method="post" asp-page-handler="Clone" style="display:inline;">
                                <input type="hidden" asp-for="@product.Id" name="id" />
                                <button type="submit" class="btn btn-outline-success flex-shrink-0">Clone</button>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
        }
    }
    else if (User.IsInRole("user"))
    {
        @foreach (var product in Model.Products)
        {
            <section class="py-5">
                <div class="container px-4 px-lg-5 my-5">
                    <div class="row gx-4 gx-lg-5 align-items-center">
                        <div class="col-md-6">
                            <img class="card-img-top mb-5 mb-md-0" src="/products/@product.ImageFileName" alt="@product.Name" />
                        </div>
                        <div class="col-md-6">
                            <div class="small mb-1">ID: @product.Id</div>
                            <h1 class="display-5 fw-bolder">@product.Name</h1>
                            <div class="fs-5 mb-5">
                                <span>@(product.Price)$</span>
                            </div>
                            <p class="lead">@product.Description</p>
                            <p><strong>Brand:</strong> @product.Brand</p>
                            <p><strong>Stock:</strong> @product.StockCount</p>
                        </div>
                    </div>
                </div>
            </section>
        }
    }
}
else
{
    @foreach (var product in Model.Products)
    {
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6">
                        <img class="card-img-top mb-5 mb-md-0" src="/products/@product.ImageFileName" alt="@product.Name" />
                    </div>
                    <div class="col-md-6">
                        <div class="small mb-1">ID: @product.Id</div>
                        <h1 class="display-5 fw-bolder">@product.Name</h1>
                        <div class="fs-5 mb-5">
                            <span>@(product.Price)$</span>
                        </div>
                        <p class="lead">@product.Description</p>
                        <p><strong>Brand:</strong> @product.Brand</p>
                        <p><strong>Stock:</strong> @product.StockCount</p>
                    </div>
                </div>
            </div>
        </section>
    }
}